apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - port: 9200
    name: elasticsearch
    targetPort: 9200
    protocol: TCP
  selector:
    app: elasticsearch
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
        app: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        ports:
        - name: elasticsearch
          containerPort: 9200
        env:
         - name: ES_JAVA_OPTS
           value: "-Xms1024m -Xmx1024m"
         - name: node.name
           value: "node-1"
         - name: cluster.name
           value: "wazuh"
         - name: network.host
           value: "0.0.0.0"
         - name: bootstrap.memory_lock
           value: "false"
        resources:
           limits:
              cpu: 200m
              memory: 2200Mi
           requests:
              cpu: 50m
              memory: 200Mi

          



