apiVersion: v1
kind: Service
metadata:
  name: wazuh-manager
spec:
  ports:
  - port: 55000
    name: wazuh-api
    targetPort: 55000
    protocol: TCP
  - port: 1515
    name: wazuh-register
    targetPort: 1515
    protocol: TCP
  - port: 1516
    name:  wazuh-tcp2
    targetPort: 1516
    protocol: TCP
  - port: 1514
    targetPort: 1514
    name: wazuh-syslog
    protocol: TCP
  selector:
    app: wazuh-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: wazuh
spec:
  ports:
  - port: 55000
    name: wazuh-api
    targetPort: 55000
    protocol: TCP
  - port: 1515
    name: wazuh-register
    targetPort: 1515
    protocol: TCP
  - port: 1516
    name:  wazuh-tcp2
    targetPort: 1516
    protocol: TCP
  - port: 1514
    targetPort: 1514
    name: wazuh-syslog
    protocol: TCP
  selector:
    app: wazuh-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: wazuh-inet
spec:
  ports:
  - port: 1515
    name: wazuh-register
    targetPort: 1515
    protocol: TCP
  - port: 1516
    name:  wazuh-tcp2
    targetPort: 1516
    protocol: TCP
  - port: 1514
    targetPort: 1514
    name: wazuh-syslog
    protocol: TCP
  selector:
    app: wazuh-server
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wazuh-server
  labels:
        app: wazuh-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wazuh-server
    spec:
      volumes:
       - name: config
         configMap:
           name: ossec-conf-v1.0
      containers:
      - name: wazuh-server
        image: wazuh/wazuh:3.8.0_6.5.4
        volumeMounts:
        - name: config
          mountPath: /wazuh-config-mount/etc/ossec.conf
          subPath: ossec.conf
          readOnly: true
        ports:
        - name: wazuh-api
          containerPort: 55000
        - name: wazuh-register
          containerPort: 1515
        - name: wazuh-tcp2
          containerPort: 1516
        - name: wazuh-syslog
          containerPort: 1514
